// <auto-generated />
using BackEnd.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Model.Programador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BancoAgencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoNumConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContaCorrente")
                        .HasColumnType("bit");

                    b.Property<bool>("ContaPoupanca")
                        .HasColumnType("bit");

                    b.Property<string>("CursoSuperior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisponibilidadeViagem")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoraAcimaOito")
                        .HasColumnType("bit");

                    b.Property<bool>("HoraAteQuatro")
                        .HasColumnType("bit");

                    b.Property<bool>("HoraQuatroAteSeis")
                        .HasColumnType("bit");

                    b.Property<bool>("HoraSeisAteOito")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioComercial")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioFinalDeSemana")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioPelaMadrugada")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioPelaManha")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioPelaNoite")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioPelaTarde")
                        .HasColumnType("bit");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portfolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PretensaoSalarial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjetoCRUDlink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programadores");
                });
#pragma warning restore 612, 618
        }
    }
}
